# This file tells netlify where the code for this project is and
# how it should build the JavaScript assets to deploy from.
[build]
  base = "code/"
  publish = "build/code/public"
  command = "CI= npm run build"
  process.env.CI = true
